application:
    build: code
    volumes:
        - ./app:/var/www/laravel
        - ./logs/laravel:/var/www/laravel/storage/logs
    tty: true
db:
    build: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: laravel
        TEST_DB_NAME: laravel_test
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    ports:
        - 3306:3307
redis:
  image: redis:alpine
  ports:
      - 6379:6379
php:
    build: php7-fpm
    environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: laravel
        TEST_DB_NAME: laravel_test
    volumes_from:
        - application
    links:
        - db
        - redis
nginx:
    build: nginx
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
    ports:
        - 80:80
elk:
    image: willdurand/elk
    volumes:
        - ./elk/logstash:/etc/logstash
        - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
        - application
        - php
        - nginx
    ports:
        - 81:80